# Custom hooks for pre-commit.


# region scripts -----------------------------------------------------------------------
- id: pyproject-validate-version
  description: "Validate python version (PEP-440)."
  entry: "./src/assorted_hooks/scripts/pyproject_validate_version.py"
  files: ^pyproject\.toml$
  language: script
  name: pyproject-validate-version
  types: [toml]
- id: pyproject-update-deps
  description: "Update dependencies to >=currently_installed. (default: manual)"
  entry: "./src/assorted_hooks/scripts/pyproject_update_dependencies.py"
  files: ^pyproject\.toml$
  language: script
  name: pyproject-update-deps
  stages: [manual]
  types: [toml]
- id: pyproject-check-deps
  description: "Check that listed dependencies are used in code and vice-versa."
  entry: "./src/assorted_hooks/scripts/pyproject_check_dependencies.py"
  files: ^pyproject\.toml$
  language: script
  name: pyproject-check-deps
  types: [toml]
- id: python-check-clean-interface
  description: "Check for clean interface."
  entry: "./src/assorted_hooks/scripts/check_clean_interface.py"
  language: script
  name: python-check-clean-interface
  require_serial: true # otherwise module is loaded multiple times
  types: [python]
# endregion scripts --------------------------------------------------------------------


# region pygrep ------------------------------------------------------------------------
- id: check-separator-length
  name: check-separator-length
  entry: ^#(.{0,83}|.{85,})([-=═─—])\2{2}$
  language: pygrep
  types: [python]
  description: "Check that 'line-break'-comments are the right length (default: 88)."
- id: python-no-blanket-type-ignore
  name: python-no-blanket-type-ignore
  entry: '.# *type: *ignore(?!\[)'
  language: pygrep
  types: [python]
  description: "Enforce that `# type: ignore` annotations always specify codes."
- id: python-no-builtin-eval
  name: python-no-builtin-eval
  entry: '(?<!def\s)(?<!\.)\b(builtins\.)?(eval\()'
  language: pygrep
  types: [python]
  description: "Disallows eval() but allows obj.eval()."
- id: python-consider-using-raw-string
  name: python-consider-using-raw-string
  entry: '\s+"""\S'
  language: pygrep
  types: [python]
  description: "Checks that triple quoted strings are raw (docstrings)."
# endregion pygrep ---------------------------------------------------------------------


# region ast-based ---------------------------------------------------------------------
- id: python-use-imported-attributes
  name: python-use-imported-attributes
  entry: check-imported-attributes
  language: python
  types: [python]
  description: "Checks that Bar is used instead of foo.Bar if both foo and Bar are imported."
- id: python-check-no-mixed-args
  name: python-check-no-mixed-args
  entry: check-no-mixed-args
  language: python
  types: [python]
  description: "Check for disallowing positional_or_keyword arguments."
- id: python-check-standard-generics
  name: python-check-standard-generics
  entry: check-standard-generics
  language: python
  types: [python]
  description: "Use standard generics (PEP-585): typing.Sequence -> abc.Sequence, typing.List -> list."
- id: python-check-dunder-all-exists
  name: python-check-dunder-all-exists
  entry: check-dunder-all-exists
  language: python
  types: [python]
  exclude: '^(.*\/)?test_.*\.py$'
  description: "Check that __all__ exists. `test_*.py` files are excluded by default."
- id: python-check-typing
  name: python-check-typing
  entry: check-typing
  language: python
  types: [python]
  description: "AST-based linting rule for type-hints."
# endregion ast-based ------------------------------------------------------------------


# region bash ------------------------------------------------------------------
- id: shellcheck
  name: shellcheck
  language: system
  types: [shell]
  description: "ShellCheck, a static analysis tool for shell scripts."
  entry: shellcheck
  args:
    - "--shell=bash"
    - "--color=always"
    - "--format=gcc"
- id: chktex
  name: chktex
  language: system
  types: [tex]
  description: "ChkTeX, a LaTeX semantic checker."
  entry: chktex
  args:
    - "--format=%f:%l:%c %m [%k %n]\n"
    - "--quiet"
    - "--erroron=all"
    - "--"
- id: lacheck
  name: lacheck
  description: "A consistency checker for LaTeX documents"
  language: system
  types: [tex]
  files: \.tex$
  entry: bash -c '! printf "%s\n" "$@" | xargs -I _ lacheck _ | grep .' --
# endregion bash ---------------------------------------------------------------
