- id: python-use-imported-attributes
  description: "Checks that Bar is used instead of foo.Bar if both foo and Bar are imported."
  entry: check-imported-attributes
  language: python
  name: python-use-imported-attributes
  types: [python]
- id: python-no-mixed-args
  description: "Check for disallowing positional_or_keyword arguments."
  entry: no-mixed-args
  language: python
  name: python-no-mixed-args
  types: [python]
- id: jupyter-clear-output
  additional_dependencies: [jupyter, nbconvert]
  description: "Remove output from jupyter notebooks."
  entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
  language: python
  name: jupyter-clear-output
  types: [jupyter]
- id: pyproject-validate-version
  description: "Validate python version (PEP-440)."
  entry: pyproject-validate-version
  files: ^pyproject\.toml$
  language: python
  name: pyproject-validate-version
- id: pyproject-update-deps
  description: "Update dependencies to >=currently_installed. (default: manual)"
  entry: "./src/assorted_hooks/pyproject_update_dependencies.py"
  files: ^pyproject\.toml$
  language: script
  name: pyproject-update-deps
  stages: [manual]
- id: pyproject-check-deps
  description: "Check that listed dependencies are used in code and vice-versa."
  entry: "./src/assorted_hooks/pyproject_check_dependencies.py"
  files: ^pyproject\.toml$
  language: script
  name: pyproject-check-deps
- id: python-no-blanket-type-ignore
  name: python-no-blanket-type-ignore
  description: "Enforce that `# type: ignore` annotations always specify codes."
  entry: '.# *type: *ignore(?!\[)'
  language: pygrep
  types: [python]
- id: python-no-builtin-eval
  name: python-no-builtin-eval
  description: "Disallows eval() but allows obj.eval()."
  entry: '((\b)builtins\.|(?<!\.))eval\('
  language: pygrep
  types: [python]
