# Custom hooks for pre-commit.

- id: python-use-imported-attributes
  description: "Checks that Bar is used instead of foo.Bar if both foo and Bar are imported."
  entry: check-imported-attributes
  language: python
  name: python-use-imported-attributes
  types: [python]
- id: python-check-no-mixed-args
  description: "Check for disallowing positional_or_keyword arguments."
  entry: check-no-mixed-args
  language: python
  name: python-check-no-mixed-args
  types: [python]
- id: pyproject-validate-version
  description: "Validate python version (PEP-440)."
  entry: pyproject-validate-version
  files: ^pyproject\.toml$
  language: python
  name: pyproject-validate-version
  types: [toml]
- id: pyproject-update-deps
  description: "Update dependencies to >=currently_installed. (default: manual)"
  entry: "./src/assorted_hooks/pyproject_update_dependencies.py"
  files: ^pyproject\.toml$
  language: script
  name: pyproject-update-deps
  stages: [manual]
  types: [toml]
- id: pyproject-check-deps
  description: "Check that listed dependencies are used in code and vice-versa."
  entry: "./src/assorted_hooks/pyproject_check_dependencies.py"
  files: ^pyproject\.toml$
  language: script
  name: pyproject-check-deps
  types: [toml]
- id: python-no-blanket-type-ignore
  description: "Enforce that `# type: ignore` annotations always specify codes."
  entry: '.# *type: *ignore(?!\[)'
  language: pygrep
  name: python-no-blanket-type-ignore
  types: [python]
- id: python-no-builtin-eval
  description: "Disallows eval() but allows obj.eval()."
  entry: '((\b)builtins\.|(?<!\.))eval\('
  language: pygrep
  name: python-no-builtin-eval
  types: [python]
- id: python-check-standard-generics
  description: "Use standard generics (PEP-585): typing.Sequence -> abc.Sequence, typing.List -> list."
  entry: check-standard-generics
  language: python
  name: python-check-standard-generics
  types: [python]
- id: check-separator-length
  description: "Check that 'line-break'-comments are the right length (default: 88)."
  entry: ^#(.{0,83}|.{85,})([-=═─—])\2{2}$
  language: pygrep
  name: check-separator-length
  types: [python]
