- id: imported-attributes
  name: imported-attributes
  description: "Check for directly imported attributes."
  entry: imported-attributes
  language: python
  types: [python]
- id: jupyter-clear-output
  name: jupyter-clear-output
  description: "Remove output from jupyter notebooks."
  additional_dependencies: [jupyter, nbconvert]
  entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
  language: python
  types: [jupyter]
- id: validate-version
  name: validate-version
  description: "Validate python version."
  entry: validate-version
  language: python
  files: ^pyproject\.toml$
