# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

minimum_prek_version = "0.5.4"
default_language_version = { python = "3.14", node = "26.3.0" }

[[repos]]
repo = "builtin"
hooks = [
    { id = "trailing-whitespace", exclude_types = ["tsv"] },
    { id = "check-added-large-files" },
    { id = "check-case-conflict" },
    { id = "check-illegal-windows-names" },
    { id = "end-of-file-fixer" },
    { id = "file-contents-sorter" },
    { id = "fix-byte-order-marker" },
    { id = "check-json" },
    { id = "check-json5" },
    # { id = "pretty-format-json" },
    { id = "check-toml" },
    { id = "check-vcs-permalinks" },
    { id = "check-yaml" },
    { id = "check-xml" },
    { id = "mixed-line-ending" },
    { id = "check-symlinks" },
    { id = "destroyed-symlinks" },
    { id = "check-merge-conflict" },
    { id = "detect-private-key" },
    # { id = "no-commit-to-branch" },
    { id = "check-shebang-scripts-are-executable" },
    { id = "check-executables-have-shebangs" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.9"
hooks = [
    {
        id = "ruff-check",
        name = "ruff-isort",
        files = "^src/|^tests/",
        args = ["--select", "I", "--fix"],
    },
    { id = "ruff-format", files = "^src/|^tests/" },
    { id = "ruff-check", files = "^src/|^tests/" },
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.12.19"
hooks = [
    { id = "uv-lock" },
    {
        id = "uv-export",
        args = ["--no-dev", "--no-hashes", "--frozen", "--output-file=requirements.txt"],
    },
    {
        id = "uv-export",
        args = ["--no-dev", "--frozen", "--output-file=pylock.toml"],
    },
]

[[repos]]
repo = "https://github.com/igorshubovych/markdownlint-cli"
rev = "v0.49.1"
hooks = [
    {
        id = "markdownlint",
        args = ["--disable", "MD013", "MD033", "--"],
    },
]

[[repos]]
repo = "https://github.com/koalaman/shellcheck-precommit"
rev = "v0.11.0"
hooks = [
    {
        id = "shellcheck",
        args = ["-x", "--shell=bash", "--color=always", "--format=gcc", "--"],
    },
]

[[repos]]
repo = "local"
hooks = [
    {
        id = "pyright-concise",
        name = "pyright-concise",
        language = "system",
        types_or = ["python", "pyi"],
        entry = "src/pyright_wrapper.sh",
        require_serial = true,
        files = "^src/|^tests/",
    }
]

[[repos]]
repo = "local"
hooks = [
    {
        id = "mypy",
        name = "mypy",
        language = "system",
        require_serial = true,
        types_or = ["python", "pyi"],
        files = "^src/|^tests/",
        entry = "mypy",
        args = ["--hide-error-context", "--hide-error-end", "--no-pretty", "--"],
    },
    {
        id = "tach",
        name = "tach",
        description = "Validate package dependencies",
        entry = "tach check",
        language = "python",
        pass_filenames = false,
    }
]
