interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [
    "src",
]

[[modules]]
path = "assorted_hooks.ast"
depends_on = ["assorted_hooks.utils"]

[[modules]]
path = "assorted_hooks.ast._clean_namespace"
depends_on = []
utility = true

[[modules]]
path = "assorted_hooks.ast._unimplemented_check_tests_folder_structure"
depends_on = []
utility = true

[[modules]]
path = "assorted_hooks.ast._unimplemented_check_typing_style"
depends_on = []
utility = true

[[modules]]
path = "assorted_hooks.ast.ast_utils"
depends_on = []

[[modules]]
path = "assorted_hooks.ast.base"
depends_on = []

[[modules]]
path = "assorted_hooks.ast.check_direct_imports"
depends_on = [
    "assorted_hooks.ast.ast_utils",
    "assorted_hooks.utils",
]
utility = true

[[modules]]
path = "assorted_hooks.ast.check_dunder_all"
depends_on = [
    "assorted_hooks.ast.ast_utils",
    "assorted_hooks.utils",
]
utility = true

[[modules]]
path = "assorted_hooks.ast.check_no_mixed_args"
depends_on = [
    "assorted_hooks.ast.ast_utils",
    "assorted_hooks.utils",
]
utility = true

[[modules]]
path = "assorted_hooks.ast.check_numpy"
depends_on = []
utility = true

[[modules]]
path = "assorted_hooks.ast.check_standard_generics"
depends_on = [
    "assorted_hooks.ast.ast_utils",
    "assorted_hooks.utils",
]
utility = true

[[modules]]
path = "assorted_hooks.ast.check_typing"
depends_on = [
    "assorted_hooks.ast.ast_utils",
    "assorted_hooks.utils",
]
utility = true

[[modules]]
path = "assorted_hooks.check_archived_hooks"
depends_on = [
    "assorted_hooks.utils",
]
utility = true

[[modules]]
path = "assorted_hooks.check_github_issues"
depends_on = [
    "assorted_hooks.utils",
]
utility = true

[[modules]]
path = "assorted_hooks.check_requirements_maintained"
depends_on = [
    "assorted_hooks.utils",
]
utility = true

[[modules]]
path = "assorted_hooks.check_requirements_valid"
depends_on = [
    "assorted_hooks.utils",
]
utility = true

[[modules]]
path = "assorted_hooks.parser"
depends_on = []

[[modules]]
path = "assorted_hooks.scripts"
depends_on = []

[[modules]]
path = "assorted_hooks.scripts.check_clean_interface"
depends_on = []
utility = true

[[modules]]
path = "assorted_hooks.scripts.check_requirements_used"
depends_on = []
utility = true

[[modules]]
path = "assorted_hooks.scripts.update_requirements"
depends_on = []
utility = true

[[modules]]
path = "assorted_hooks.utils"
depends_on = []
