interfaces = []
exclude = [
	"**/*__pycache__",
	"**/*egg-info",
	"**/docs",
	"**/tests",
	"**/venv",
]
source_roots = [ "src/assorted_hooks",
]

[[modules]]
path = "ast.base"
depends_on = ["ast"]

[[modules]]
path = "utils"
depends_on = []

[[modules]]
path = "ast"
depends_on = ["ast.ast_utils"]

[[modules]]
path = "constants"
depends_on = []

[[modules]]
path = "ast.ast_utils"
depends_on = ["ast"]

[[modules]]
path = "parser"
depends_on = []
